version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.10-management"
    ports:
      - "15672:15672"
      - "5672:5672"

  # app:
  #   container_name: app
  #   build: .
  #   ports:
  #     - "2000:2000"
